con:
  token: '' # Discord bot token
  websocket: 19132 # Music dashboard websocket port
# vote:
#   webhook: # webhook port
#   auth: # webhook auth (from vote site)

mysql: # MySQL database credentials
  host: ''
  user: ''
  password: ''
  database: ''

music:
  lavalink:
    identifier: '' # lavalink node name
    host: '' # lavalink node host ip
    port: 2333
    password: ''
    retryAmount: 3
    retryDelay: 5000
    secure: false

dashboard:
  port: 6969
  domain: 'http://localhost:6969' # Dashboard domain
  clientSecret: '' # Client Secret from dev panel
  debug: false # Save sessions in a JSON file. ONLY FOR DEBUGGING, NEVER USE ON PROD.